import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import test from 'node:test';

test('daily detail layout exposes desktop collapse and mobile drawer contracts', () => {
  assert.equal(existsSync('src/components/daily/daily-detail-layout.tsx'), true);

  const layout = readFileSync('src/components/daily/daily-detail-layout.tsx', 'utf8');
  const detail = readFileSync('src/components/daily/daily-detail.tsx', 'utf8');
  const detailShell = readFileSync('src/components/daily/daily-detail-shell.tsx', 'utf8');
  const contentHeader = readFileSync('src/components/content/content-header.tsx', 'utf8');
  const tagFilterBar = readFileSync('src/components/content/tag-filter-bar.tsx', 'utf8');
  const tagFilterBarCss = readFileSync('src/components/content/tag-filter-bar.module.css', 'utf8');
  const experience = readFileSync('src/components/daily/daily-experience.tsx', 'utf8');
  const feedPane = readFileSync('src/components/daily/daily-feed-pane.tsx', 'utf8');
  const tagFilters = readFileSync('src/components/daily/daily-tag-filters.tsx', 'utf8');
  const serverFeed = readFileSync('src/components/daily/daily-server-feed.tsx', 'utf8');
  const virtualTimeline = readFileSync('src/components/daily/virtual-timeline.tsx', 'utf8');
  const detailLoading = readFileSync('src/app/daily/(detail)/[id]/loading.tsx', 'utf8');
  const markdownContent = readFileSync('src/components/markdown-content.tsx', 'utf8');
  const css = readFileSync('src/app/daily/page.module.css', 'utf8');
  const navCss = readFileSync('src/components/nav.module.css', 'utf8');

  assert.match(layout, /data-feed-collapsed/);
  assert.match(layout, /data-feed-drawer-open/);
  assert.match(layout, /data-feed-transition-state/);
  assert.match(layout, /FEED_COLLAPSE_TRANSITION_MS/);
  assert.match(layout, /feedTransitionState/);
  assert.match(layout, /window\.setTimeout/);
  assert.match(layout, /daily-feed-panel/);
  assert.match(layout, /sessionStorage/);
  assert.match(layout, /DAILY_ENTRY_LINK_SELECTOR/);
  assert.match(layout, /target\.closest\(DAILY_ENTRY_LINK_SELECTOR\)/);
  assert.doesNotMatch(layout, /target\.closest\(`\.\$\{styles\.feedPane\} a`\)/);
  assert.match(layout, /detailPaneRef\.current\?\.scrollTo\(0,\s*0\)/);
  assert.match(layout, /window\.scrollTo\(0,\s*0\)/);
  assert.match(layout, /floatingFeedToggle/);
  assert.match(layout, /desktopFloatingFeedToggle/);
  assert.match(layout, /mobileFloatingFeedToggle/);
  assert.match(layout, /ChevronLeftIcon/);
  assert.match(layout, /ChevronRightIcon/);
  assert.match(layout, /aria-label=\{isFeedDrawerOpen \? '收起笔记列表' : '打开笔记列表'\}/);
  assert.match(layout, /setIsFeedDrawerOpen\(\(isOpen\) => !isOpen\)/);
  assert.doesNotMatch(layout, /XIcon|feedDrawerCloseButton|aria-label="关闭笔记列表"|MenuFoldIcon|MenuUnfoldIcon|ViewListIcon|ArrowLeftIcon|ArrowRightIcon/);
  assert.doesNotMatch(layout, /detailPaneControls/);
  assert.match(contentHeader, /Badge/);
  assert.match(contentHeader, /ArrowLeftIcon/);
  assert.match(detail, /ContentHeader/);
  assert.match(detail, /backHref=\{closeHref\}/);
  assert.match(detail, /backScroll=\{false\}/);
  assert.match(detail, /entry\.type === 'deep-share'/);
  assert.match(detail, /metadata=\{\[\{ key: 'date', label: entry\.date, dateTime: entry\.date \}\]\}/);
  assert.match(detail, /MarkdownContent/);
  assert.match(detail, /assetBasePath="\/daily\/"/);
  assert.doesNotMatch(detail, /MDXRemote|mdxComponents/);
  assert.doesNotMatch(detailShell, /XIcon|styles\.closeButton|aria-label="关闭详情"/);
  assert.match(experience, /DailyDetailLayout/);
  assert.match(experience, /DailyTagFilters/);
  assert.doesNotMatch(experience, /navigationKey/);
  assert.match(experience, /feedResetKey/);
  assert.match(experience, /resetKey=\{feedResetKey\}/);
  assert.doesNotMatch(experience, /<DailyFeedPane id=\{FEED_PANEL_ID\} resetKey=\{navigationKey\}>/);
  assert.match(tagFilters, /'use client'/);
  assert.match(tagFilterBar, /prefetch=\{item\.prefetch\}/);
  assert.match(tagFilters, /prefetch:\s*true/);
  assert.match(tagFilters, /TagFilterBar/);
  assert.match(tagFilters, /onItemClick=\{handleItemClick\}/);
  assert.match(tagFilters, /optimisticActiveTag/);
  assert.doesNotMatch(tagFilters, /useLinkStatus/);
  assert.doesNotMatch(tagFilters, /data-pending/);
  assert.doesNotMatch(tagFilters, /TagFilterPendingHint/);
  assert.match(feedPane, /id\?: string/);
  assert.match(feedPane, /resetKey: string/);
  assert.match(feedPane, /FEED_SCROLL_STORAGE_PREFIX/);
  assert.match(feedPane, /window\.sessionStorage\.getItem/);
  assert.match(feedPane, /window\.sessionStorage\.setItem/);
  assert.match(feedPane, /useCallback/);
  assert.match(feedPane, /restorePaneRef/);
  assert.match(feedPane, /onPointerDownCapture=\{saveScrollTopNow\}/);
  assert.match(feedPane, /onClickCapture=\{saveScrollTopNow\}/);
  assert.doesNotMatch(feedPane, /pane\.scrollTop = 0/);
  assert.match(serverFeed, /data-daily-entry-link="true"/);
  assert.match(serverFeed, /MarkdownContent/);
  assert.match(serverFeed, /assetBasePath="\/daily\/"/);
  assert.doesNotMatch(serverFeed, /MDXRemote|mdxComponents/);
  assert.match(virtualTimeline, /data-daily-entry-link="true"/);
  assert.match(virtualTimeline, /MarkdownContent/);
  assert.match(virtualTimeline, /assetBasePath="\/daily\/"/);
  assert.doesNotMatch(virtualTimeline, /MDXRemote|mdxComponents/);
  assert.match(markdownContent, /MarkdownRender/);
  assert.match(markdownContent, /function normalizeAssetUrl/);
  assert.match(markdownContent, /img: \(\{ src, \.\.\.props \}\)/);
  assert.match(markdownContent, /normalizeAssetUrl\(src, assetBasePath\)/);
  assert.match(markdownContent, /variant="h2"/);
  assert.match(detailLoading, /DailyDetailLoading/);
  assert.doesNotMatch(detailLoading, /DailyExperience/);
  assert.doesNotMatch(detailLoading, /detailLoading/);
  assert.match(css, /experienceSplit\[data-feed-collapsed="true"\]/);
  assert.match(css, /experienceSplit\[data-feed-drawer-open="true"\]/);
  assert.match(css, /align-items:\s*stretch/);
  assert.match(css, /\.detailPane\s*{[\s\S]*padding-left:\s*clamp\(24px,\s*3vw,\s*48px\);[\s\S]*padding-right:\s*clamp\(24px,\s*3vw,\s*48px\);/);
  assert.match(css, /\.detailContentHeader\s*{[\s\S]*margin-bottom:\s*28px;/);
  assert.match(css, /\.body :global\(img\)\s*{[\s\S]*width:\s*100%;[\s\S]*max-width:\s*100%;[\s\S]*box-sizing:\s*border-box;/);
  assert.match(css, /\.detailArticle \.body > :global\(:first-child\)\s*{[\s\S]*margin-top:\s*0 !important;/);
  assert.match(css, /\.detailArticle \.body > :global\(:first-child > :first-child\)\s*{[\s\S]*margin-top:\s*0 !important;/);
  assert.match(css, /@media \(max-width: 768px\)[\s\S]*\.timelineSplitMode\s*{[\s\S]*height:\s*auto;[\s\S]*overflow:\s*visible;/);
  assert.match(css, /@media \(max-width: 768px\)[\s\S]*\.detailTitle\s*{[\s\S]*font-size:\s*2\.5rem;/);
  assert.match(css, /@media \(max-width: 768px\)[\s\S]*--feed-drawer-width:\s*min\(88vw,\s*420px,\s*calc\(100vw - 32px\)\);/);
  assert.match(css, /@media \(max-width: 768px\)[\s\S]*\.feedSlot\s*{[\s\S]*width:\s*var\(--feed-drawer-width\);/);
  assert.doesNotMatch(css, /--button-background:\s*color-mix/);
  assert.doesNotMatch(css, /--button-border-color:\s*color-mix/);
  assert.match(css, /\.experienceSplit\s*{[\s\S]*position:\s*relative;/);
  assert.match(css, /\.feedToggleButton\.floatingFeedToggle\s*{[\s\S]*--split-width:\s*min\(calc\(100% - \(clamp\(16px,\s*2\.5vw,\s*40px\) \* 2\)\),\s*1440px\);[\s\S]*--feed-toggle-ratio:\s*0\.4505494505;[\s\S]*--feed-toggle-x:\s*-100%;[\s\S]*--feed-toggle-inset:\s*16px;[\s\S]*position:\s*fixed;[\s\S]*top:\s*auto;[\s\S]*bottom:\s*max\(24px,\s*calc\(env\(safe-area-inset-bottom\) \+ 24px\)\);[\s\S]*left:\s*calc\(\(\(100% - var\(--split-width\)\) \/ 2\) \+ \(var\(--split-width\) \* var\(--feed-toggle-ratio\)\) - var\(--feed-toggle-inset\)\);[\s\S]*opacity:\s*0\.78/);
  assert.match(css, /\.feedToggleButton\.mobileFloatingFeedToggle\s*{[\s\S]*display:\s*none;/);
  assert.match(css, /\.feedToggleButton\.floatingFeedToggle\s*{[\s\S]*width:\s*40px;[\s\S]*height:\s*40px;[\s\S]*min-width:\s*40px;[\s\S]*min-height:\s*40px;[\s\S]*padding:\s*0;[\s\S]*border-radius:\s*999px;/);
  assert.match(css, /@media \(max-width: 768px\)[\s\S]*\.feedToggleButton\.floatingFeedToggle\s*{[\s\S]*width:\s*44px;[\s\S]*height:\s*44px;/);
  assert.match(css, /@media \(max-width: 768px\)[\s\S]*\.feedToggleButton\.floatingFeedToggle\s*{[\s\S]*--feed-toggle-x:\s*16px;[\s\S]*--feed-toggle-inset:\s*0px;[\s\S]*position:\s*fixed;[\s\S]*left:\s*0;[\s\S]*top:\s*auto;[\s\S]*bottom:\s*max\(20px,\s*calc\(env\(safe-area-inset-bottom\) \+ 20px\)\);/);
  assert.match(css, /@media \(max-width: 768px\)[\s\S]*\.feedToggleButton\.floatingFeedToggle\s*{[\s\S]*z-index:\s*31;/);
  assert.match(css, /\.feedToggleButton\.floatingFeedToggle\s*{[\s\S]*display:\s*inline-flex;[\s\S]*align-items:\s*center;[\s\S]*justify-content:\s*center;/);
  assert.match(css, /\.feedToggleButton\.floatingFeedToggle\s*{[\s\S]*border:\s*1px solid var\(--ui-color-border\);[\s\S]*background:\s*color-mix\(in srgb,\s*var\(--ui-color-canvas\) 92%,\s*transparent\);/);
  assert.match(css, /\.experienceSplit\[data-feed-collapsed="true"\]\s+\.feedSlot\s*{[\s\S]*transform:\s*translate3d\(-24px,\s*0,\s*0\);/);
  assert.match(css, /\.experienceSplit\[data-feed-transition-state="collapsing"\]\s+\.feedSlot\s*{[\s\S]*opacity:\s*0;[\s\S]*transform:\s*translate3d\(-24px,\s*0,\s*0\);/);
  assert.match(css, /\.experienceSplit\[data-feed-transition-state="expanding"\]\s+\.feedSlot\s*{[\s\S]*animation:\s*feed-enter-after-layout/);
  assert.match(css, /@keyframes feed-enter-after-layout\s*{[\s\S]*0%,\s*58%\s*{[\s\S]*opacity:\s*0;[\s\S]*transform:\s*translate3d\(-24px,\s*0,\s*0\);[\s\S]*100%\s*{[\s\S]*opacity:\s*1;[\s\S]*transform:\s*translate3d\(0,\s*0,\s*0\);/);
  assert.doesNotMatch(css, /\.experienceSplit\[data-feed-collapsed="true"\]\s*{[\s\S]*grid-template-columns:\s*0 minmax\(0,\s*1fr\);/);
  assert.match(css, /--button-ghost-background-hover:\s*color-mix\(in srgb,\s*var\(--ui-color-canvas\) 96%,\s*var\(--ui-color-text\) 4%\)/);
  assert.doesNotMatch(css, /\.closeButton/);
  assert.match(tagFilterBarCss, /\.item\[data-active="true"\]\s*{[^}]*color:\s*var\(--ui-color-brand-text\)/);
  assert.match(tagFilterBarCss, /\.item\[data-active="true"\]\s*{[^}]*border-color:\s*var\(--ui-color-brand-text\)/);
  assert.match(tagFilterBarCss, /\.item\[data-active="true"\]\s*{[^}]*background:\s*color-mix\(in srgb,\s*var\(--ui-color-brand-text\)/);
  assert.doesNotMatch(css, /\.tagFilterPendingHint\s*{/);
  assert.doesNotMatch(css, /\.tagFilter\[data-pending="true"\]\s+\.tagFilterPendingHint/);
  assert.match(navCss, /--button-ghost-background-hover:\s*transparent/);
  assert.match(css, /\.feedToggleButton\.floatingFeedToggle\s*{[\s\S]*transition:[^;]*transform[^;]*opacity/);
  assert.match(css, /\.feedToggleButton\.floatingFeedToggle:hover,[\s\S]*\.feedToggleButton\.floatingFeedToggle:focus-visible\s*{[\s\S]*opacity:\s*1/);
  assert.match(css, /experienceSplit\[data-feed-collapsed="true"\]\s+\.desktopFloatingFeedToggle/);
  assert.match(css, /\.experienceSplit\[data-feed-collapsed="true"\]\s+\.desktopFloatingFeedToggle\s*{[\s\S]*--feed-toggle-ratio:\s*0\.0740740741;[\s\S]*--feed-toggle-x:\s*0;[\s\S]*--feed-toggle-inset:\s*0px;/);
  assert.match(css, /experienceSplit\[data-feed-drawer-open="true"\]\s+\.mobileFloatingFeedToggle\s*{[\s\S]*--feed-toggle-x:\s*calc\(var\(--feed-drawer-width\) - 56px\);[\s\S]*opacity:\s*0\.9;/);
  assert.doesNotMatch(css, /feedDrawerCloseButton/);
  assert.doesNotMatch(css, /experienceSplit\[data-feed-drawer-open="true"\]\s+\.mobileFloatingFeedToggle\s*{[^}]*visibility:\s*hidden;/);
  assert.doesNotMatch(css, /\.detailLoading\s*{/);
  assert.match(css, /\.detailArticleLoading\s*{/);
  assert.match(css, /\.detailBackLink\s*{/);
});
