export const HOME = {
  hero: {
    location: 'SHENZHEN',
    timezone: 'CST',
    figLabel: 'FIG. 01',
    selfLabel: 'SELF',
    nameEn: 'Dewey Ou',
    nameSep: '·',
    nameZh: '欧怼怼',
    pronunciation: 'ŌU · /oʊ/',
    estLabel: 'EST · 2018',
    headlinePre: '做',
    headlineHighlight: '有意思',
    headlinePost: '的产品',
    subline: '—— 也，过有意思的生活。',
    bio: [
      { text: '字节跳动的' },
      { text: '前端工程师', variant: 'underline' as const },
      { text: '，住在深圳。喜欢有设计感、人性化、新颖的东西，也想成为做这类产品的人。最近在和 ' },
      { text: 'AI', variant: 'chip' as const },
      { text: ' 交朋友，让它陪我学习、做有意思的产品。工作之余，看书、玩魔方、变魔术、拍照。' },
    ],
    cta: '读我写的文章',
  },
} as const;
